"""Dev batch dispatch — Claude Code (Opus) subprocess + branch + per-task commits + PR.

Triggered by admin clicking "Run all approved" on /admin/dev-requests. Spawns Claude Code
in a tmux session (Glimi-Claude-Code-Dev) with a single prompt containing N approved task
briefs. Claude Code commits each task separately on a new branch
`dev-requests/run-{YYYYMMDD-HHMMSS}` cut from develop, then pushes the branch and we
auto-create a PR targeting develop.

Output protocol (Claude Code emits these markers in stdout):
  <<TASK_DONE id=42 sha=abc123>>     — successful per-task commit
  <<TASK_FAILED id=43 reason=...>>    — per-task failure (others continue)
  <<RUN_DONE>>                        — entire batch finished
  <<RUN_ABORT reason=...>>            — fatal abort (no commits)

Status transitions handled by this module:
  queued → processing  (mark_processing per task)
  processing → completed (mark_completed with commit_sha)
  processing → failed   (mark_failed with reason)

Branch / PR lifecycle handled by this module:
  - branch create from develop
  - branch push at end of run
  - `gh pr create` targeting develop
  - PR URL stored on dev_runs row + each completed dev_requests row
"""
from __future__ import annotations

import asyncio
import json as _json
import os
import re as _re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src import log_writer
from src.core import dev_agent

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OPUS_MODEL = "claude-opus-4-7"
DISPATCH_TIMEOUT_SEC = 1800  # 30 min — N개 task 처리에 충분
TARGET_BRANCH = "develop"     # PR target


# ── Branch + git helpers ──────────────────────────────────

def _run_git(*args: str, cwd: Path = PROJECT_ROOT, timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, timeout=timeout,
    )


def _make_branch_name() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"dev-requests/run-{ts}"


def _checkout_new_branch(branch_name: str) -> tuple[bool, str]:
    """develop 으로부터 새 브랜치 생성 + 체크아웃. (ok, error_msg)."""
    # develop 최신화
    fetch = _run_git("fetch", "origin", TARGET_BRANCH)
    if fetch.returncode != 0:
        return False, f"git fetch origin {TARGET_BRANCH} failed: {fetch.stderr[:200]}"
    # 새 브랜치 생성 (origin/develop 기준)
    co = _run_git("checkout", "-B", branch_name, f"origin/{TARGET_BRANCH}")
    if co.returncode != 0:
        return False, f"git checkout -B {branch_name} failed: {co.stderr[:200]}"
    return True, ""


def _push_branch(branch_name: str) -> tuple[bool, str]:
    push = _run_git("push", "-u", "origin", branch_name)
    if push.returncode != 0:
        return False, push.stderr[:300]
    return True, ""


def _create_pr(branch_name: str, requests: list[dict]) -> tuple[Optional[str], str]:
    """gh CLI 로 PR 생성. 반환: (pr_url 또는 None, error_msg)."""
    body_lines = [
        f"Auto-generated by 한세나 dev-batch run on {branch_name}.",
        "",
        f"## Requests ({len(requests)})",
    ]
    for r in requests:
        commit = r.get("commit_sha") or "(no commit)"
        body_lines.append(
            f"- #{r['id']} [{r.get('community_id','?')}] {(r.get('sera_summary') or '')[:80]} — {commit}"
        )
    title = f"Dev batch {branch_name.split('/')[-1]} ({len(requests)} requests)"

    proc = subprocess.run(
        ["gh", "pr", "create",
         "--base", TARGET_BRANCH,
         "--head", branch_name,
         "--title", title,
         "--body", "\n".join(body_lines)],
        cwd=str(PROJECT_ROOT), capture_output=True, text=True, timeout=120,
    )
    if proc.returncode != 0:
        return None, f"gh pr create failed: {proc.stderr[:300]}"
    out = proc.stdout.strip()
    # 출력 마지막 라인이 PR URL
    pr_url = next((l for l in reversed(out.splitlines()) if l.startswith("http")), out)
    return pr_url, ""


# ── Prompt building ────────────────────────────────────────

def _build_batch_prompt(run_id: int, branch_name: str, requests: list[dict]) -> str:
    """N 개 task 묶은 단일 prompt. payload_json 은 JSON string 으로 DB 에 저장돼있음."""
    lines = [
        f"You are Claude Code processing dev-batch run #{run_id} on branch `{branch_name}`.",
        "",
        "There are N approved tasks below. Process them sequentially:",
        "  - For each task: read relevant code, make minimal changes, then `git add` and",
        "    `git commit` with a short, conventional message.",
        "  - After each commit, output exactly:",
        "      <<TASK_DONE id={id} sha={short_sha}>>",
        "    where short_sha is the first 12 chars of HEAD's sha after the commit.",
        "  - If a task is genuinely impossible to do safely (touches DB schema, .env,",
        "    requires architectural decision), skip it and output:",
        "      <<TASK_FAILED id={id} reason=...>>",
        "  - DO NOT push the branch — the runner does that after you're done.",
        "  - DO NOT create files outside the project, modify .env, or touch analysis/.",
        "  - Continue to next task even if one fails.",
        "",
        "Commit message rules (CLAUDE.md):",
        "  - Short 1-line title. Optional 1-2 line body.",
        "  - **NEVER include `Co-Authored-By: Claude` or any AI co-author trailer.**",
        "  - **No `🤖 Generated with Claude Code` lines.**",
        "  - Author = project git config (jbsim) — do not override.",
        "",
        "When ALL tasks are processed (success or failure), output exactly one final line:",
        "  <<RUN_DONE>>",
        "",
        "If something catastrophically fails (e.g. cannot checkout branch, repo state weird),",
        "abort with:",
        "  <<RUN_ABORT reason=...>>",
        "",
        "─" * 60,
        f"## Tasks ({len(requests)})",
        "",
    ]

    for idx, r in enumerate(requests, 1):
        try:
            payload = _json.loads(r.get("payload_json") or "{}")
        except Exception:
            payload = {}
        files_hint = []
        try:
            files_hint = _json.loads(r.get("files_hint") or "[]") or []
        except Exception:
            pass
        lines.extend([
            f"### Task {idx} — id={r['id']} (community: {r.get('community_id','?')})",
            f"  Severity: {r.get('severity','?')} · Confidence: {r.get('confidence','?')}",
            f"  Sera summary: {(r.get('sera_summary') or '').strip()}",
            "",
            "  **Original report:**",
            f"    Channel: {payload.get('channel','?')}",
            f"    Repro:    {payload.get('repro','?')}",
            f"    Expected: {payload.get('expected','?')}",
            f"    Actual:   {payload.get('actual','?')}",
        ])
        if payload.get("notes"):
            lines.append(f"    Notes:    {payload['notes']}")
        lines.extend([
            "",
            "  **Task brief (do this):**",
            f"    {(r.get('task_brief') or '').strip()}",
        ])
        if files_hint:
            lines.append(f"    Files hint: {', '.join(files_hint)}")
        if r.get("analysis_notes"):
            lines.append(f"    Analysis notes: {r['analysis_notes']}")
        lines.append("")
        lines.append("─" * 40)
        lines.append("")

    lines.append("Begin with Task 1.")
    return "\n".join(lines)


# ── Output parsing ─────────────────────────────────────────

_TASK_DONE_RE = _re.compile(r"<<TASK_DONE\s+id=(\d+)\s+sha=([0-9a-fA-F]+)>>")
_TASK_FAILED_RE = _re.compile(r"<<TASK_FAILED\s+id=(\d+)\s+reason=(.+?)>>", _re.DOTALL)
_RUN_DONE_RE = _re.compile(r"<<RUN_DONE>>")
_RUN_ABORT_RE = _re.compile(r"<<RUN_ABORT\s+reason=(.+?)>>", _re.DOTALL)


def parse_run_output(text: str) -> dict:
    """Output text 에서 마커들 추출. 부분 stream 도 OK (라이브 polling 용)."""
    completed: list[tuple[int, str]] = []
    failed: list[tuple[int, str]] = []
    for m in _TASK_DONE_RE.finditer(text):
        completed.append((int(m.group(1)), m.group(2)[:12]))
    for m in _TASK_FAILED_RE.finditer(text):
        failed.append((int(m.group(1)), m.group(2).strip()[:200]))
    abort_m = _RUN_ABORT_RE.search(text)
    return {
        "completed": completed,
        "failed": failed,
        "run_done": bool(_RUN_DONE_RE.search(text)),
        "run_abort": abort_m.group(1).strip()[:300] if abort_m else None,
    }


# ── Top-level batch run ────────────────────────────────────

async def run_batch(
    run_id: int,
    branch_name: str,
    request_ids: list[int],
    log_path: Optional[str] = None,
) -> dict:
    """approved 요청 N개 일괄 dispatch. tmux runner 가 이 함수 호출.

    1) develop 에서 branch 생성
    2) requests 로드 + 단일 prompt 빌드
    3) Claude Code subprocess 실행 (output 을 log_path 로 tee)
    4) 마커 파싱해서 task 별 status 업데이트
    5) branch push + PR 생성
    6) dev_runs row 갱신
    """
    dev_agent.update_run_status(run_id, "running")

    # 1. branch
    ok, err = _checkout_new_branch(branch_name)
    if not ok:
        dev_agent.update_run_status(run_id, "failed", error=err)
        for rid in request_ids:
            dev_agent.mark_failed(rid, f"branch setup: {err}")
        return {"ok": False, "error": err}

    # 2. load requests + build prompt
    requests = [dev_agent.get_request(rid) for rid in request_ids]
    requests = [r for r in requests if r]
    if not requests:
        err = "no valid requests in batch"
        dev_agent.update_run_status(run_id, "failed", error=err)
        return {"ok": False, "error": err}

    prompt = _build_batch_prompt(run_id, branch_name, requests)

    for rid in request_ids:
        dev_agent.mark_processing(rid)

    # 3. subprocess
    # ⚠ dev 자동 코드 수정(Opus claude)은 비활성화됨 — 아래 _run_subprocess 의 claude 호출 주석 처리.
    #    여기서 먼저 차단해 claude 를 부르지 않고 깔끔하게 종료 (오류 없이 요청만 failed 마킹).
    #    재활성화: GLIMI_DEV_DISPATCH=1 환경변수 + _run_subprocess 내부 주석 해제.
    if os.environ.get("GLIMI_DEV_DISPATCH", "").strip().lower() not in ("1", "true", "on"):
        msg = "dev 자동 코드 수정 비활성화 (claude Opus subprocess 주석 처리됨)"
        log_writer.system(f"[dev] run #{run_id} skip — {msg}")
        dev_agent.update_run_status(run_id, "failed", error=msg)
        for rid in request_ids:
            dev_agent.mark_failed(rid, msg)
        return {"ok": False, "error": msg}

    log_writer.system(f"[dev] run #{run_id} starting Claude Code subprocess ({len(requests)} tasks)")

    full_output = []  # for parsing at end

    def _run_subprocess() -> subprocess.CompletedProcess:
        # === 비활성화: dev 자동 코드 수정 Opus 호출 (주석 처리, 삭제 금지) ===
        # 위 가드(GLIMI_DEV_DISPATCH)가 여기 도달 전에 차단하므로 보통 호출 안 됨.
        # 재활성화하려면 아래 return 주석 해제 + GLIMI_DEV_DISPATCH=1 설정.
        # return subprocess.run(
        #     ["claude", "-p", prompt,
        #      "--model", OPUS_MODEL,
        #      "--permission-mode", "bypassPermissions",
        #      "--output-format", "text"],
        #     cwd=str(PROJECT_ROOT),
        #     capture_output=True,
        #     text=True,
        #     timeout=DISPATCH_TIMEOUT_SEC,
        #     env={**os.environ, "CLAUDE_CODE_DISABLE_NONESSENTIAL": "1"},
        # )
        # 가드를 우회해 여기 도달한 경우라도 claude 를 부르지 않고 안전하게 실패시킴.
        # (아래 except Exception 핸들러가 받아 요청을 failed 로 마킹 — 크래시 없음.)
        raise RuntimeError("dev dispatch disabled — claude subprocess 주석 처리됨 (GLIMI_DEV_DISPATCH=1 로 재활성화)")

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(None, _run_subprocess)
    except subprocess.TimeoutExpired:
        err = f"Claude Code timeout after {DISPATCH_TIMEOUT_SEC}s"
        dev_agent.update_run_status(run_id, "failed", error=err)
        for rid in request_ids:
            dev_agent.mark_failed(rid, "timeout")
        return {"ok": False, "error": err}
    except FileNotFoundError:
        err = "claude CLI not found in PATH"
        dev_agent.update_run_status(run_id, "failed", error=err)
        for rid in request_ids:
            dev_agent.mark_failed(rid, err)
        return {"ok": False, "error": err}
    except Exception as e:
        err = f"{type(e).__name__}: {e}"
        dev_agent.update_run_status(run_id, "failed", error=err)
        for rid in request_ids:
            dev_agent.mark_failed(rid, err)
        return {"ok": False, "error": err}

    out = result.stdout or ""
    full_output.append(out)
    if log_path:
        try:
            Path(log_path).parent.mkdir(parents=True, exist_ok=True)
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(out)
        except Exception:
            pass

    parsed = parse_run_output(out)

    if parsed["run_abort"]:
        err = f"aborted: {parsed['run_abort']}"
        dev_agent.update_run_status(run_id, "aborted", error=err)
        for rid in request_ids:
            dev_agent.mark_failed(rid, err)
        return {"ok": False, "error": err}

    # 4. per-task status update
    completed_ids = {rid for rid, _ in parsed["completed"]}
    failed_ids = {rid for rid, _ in parsed["failed"]}
    for rid, sha in parsed["completed"]:
        req = dev_agent.get_request(rid)
        result_summary = {"sha": sha, "summary": (req.get("sera_summary") or "")[:200] if req else ""}
        dev_agent.mark_completed(rid, result_summary, commit_sha=sha)
    for rid, reason in parsed["failed"]:
        dev_agent.mark_failed(rid, reason)
    # batch 안에 있던 요청 중 마커 안 나온 것은 unknown failure 로 마킹
    for rid in request_ids:
        if rid not in completed_ids and rid not in failed_ids:
            dev_agent.mark_failed(rid, "no completion marker (Claude Code may have stopped early)")

    if not parsed["completed"]:
        err = "no successful tasks (all failed or no markers)"
        dev_agent.update_run_status(run_id, "failed", error=err,
                                    failed_count=len(request_ids))
        return {"ok": False, "error": err}

    # 5. push + PR
    push_ok, push_err = _push_branch(branch_name)
    if not push_ok:
        dev_agent.update_run_status(run_id, "failed", error=f"push: {push_err}",
                                    completed_count=len(parsed["completed"]),
                                    failed_count=len(parsed["failed"]))
        return {"ok": False, "error": f"push failed: {push_err}"}

    # PR 생성용 — completed 된 request 들의 최신 정보 reload
    completed_requests = [dev_agent.get_request(rid) for rid, _ in parsed["completed"]]
    completed_requests = [r for r in completed_requests if r]
    pr_url, pr_err = _create_pr(branch_name, completed_requests)
    if pr_url:
        dev_agent.update_run_status(run_id, "completed", pr_url=pr_url,
                                    completed_count=len(parsed["completed"]),
                                    failed_count=len(parsed["failed"]))
        # 각 완료 task 에 PR URL 매핑
        for rid, _sha in parsed["completed"]:
            req = dev_agent.get_request(rid)
            if req:
                dev_agent.mark_completed(rid, {"sha": _sha,
                                               "summary": (req.get("sera_summary") or "")[:200]},
                                         commit_sha=_sha, pr_url=pr_url)
    else:
        dev_agent.update_run_status(run_id, "completed",
                                    completed_count=len(parsed["completed"]),
                                    failed_count=len(parsed["failed"]),
                                    error=f"PR create failed: {pr_err}")

    log_writer.system(
        f"[dev] run #{run_id} done — {len(parsed['completed'])} completed, "
        f"{len(parsed['failed'])} failed, PR: {pr_url or 'none'}"
    )
    return {
        "ok": True,
        "run_id": run_id,
        "branch": branch_name,
        "pr_url": pr_url,
        "completed": len(parsed["completed"]),
        "failed": len(parsed["failed"]),
    }


__all__ = ["run_batch", "_make_branch_name", "parse_run_output", "TARGET_BRANCH"]
